# GENERATE TIME: Sun Nov 27 00:55:18 2022
# CMD:
# basicsr/train.py --local_rank=0 -opt options/train_AdaCode_stage3.yaml --launcher pytorch

# general settings
name: AdaCode_stage3_SR_X2
model_type: FeMaSRModel 
scale: &upscale 2
num_gpu: 8 # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: General_Image_Train
    # type: BSRGANTrainDataset 
    # datafile_gt: /newDisk/users/liukechun/research/FeMaSR/data/category_data/train/all_train.txt
    type: PairedImageDataset  
    datafile_gt: ./data/category_data/train/all_train.txt
    datafile_lq: ./data/category_data/train/all_train_X2.txt
    io_backend:
      type: disk
 
    gt_size: 256
    use_resize_crop: true
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    batch_size_per_gpu: &bsz 8 
    num_worker_per_gpu: *bsz 
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz

  val:
    name: General_Image_Valid
    type: PairedImageDataset
    datafile_gt: ./data/category_data/valid/all_valid.txt
    datafile_lq: ./data/category_data/valid/all_valid_X2.txt
    # crop_eval_size: 384 
    io_backend:
      type: disk

# network structures
network_g:
  type: AdaCodeSRNet_Contrast
  gt_resolution: 256
  norm_type: 'gn'
  act_type: 'silu'
  scale_factor: *upscale
  
  ### TODO: modify the configuration carefully
  AdaCode_stage: true
  LQ_stage: true
  frozen_module_keywords: ['quantize', 'decoder', 'after_quant_group', 'out_conv']

  weight_softmax: false

network_d:
  type: UNetDiscriminatorSN 
  num_in_ch: 3

# path
path:
  # pretrain_codebook:
  #   - ./experiments/AdaCode_stage1_c0_codebook512x256/models/net_g_best_.pth
  #   - ./experiments/AdaCode_stage1_c1_codebook256x256/models/net_g_best_.pth
  #   - ./experiments/AdaCode_stage1_c2_codebook512x256/models/net_g_best_.pth
  #   - ./experiments/AdaCode_stage1_c3_codebook256x256/models/net_g_best_.pth
  #   - ./experiments/AdaCode_stage1_ffhq_codebook256x256/models/net_g_best_.pth

  pretrain_network_hq: ./experiments/stage2/AdaCode_stage2_recon/models/net_g_best_.pth
  # pretrain_network_g: ~
  pretrain_network_d: ./experiments/stage2/AdaCode_stage2_recon/models/net_d_best_.pth
  strict_load: false 
  # resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [18000, 36000, 54000, 72000, 90000, 108000, 126000]
    gamma: 1 

  total_iter: 730000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0 
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: !!float 1.0 
    
  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 0.1

  codebook_opt:
    loss_weight: 1.0
  
  semantic_opt:
    loss_weight: 0.1 

  before_quant_opt: 
    loss_weight: 0.0

  after_quant_opt: 
    loss_weight: 1.0

  contrast_opt:
    loss_weight: 1.0

  net_d_iters: 1
  net_d_init_iters: !!float 0 

# validation settings·
val:
  val_freq: !!float 3e3
  save_img: false

  key_metric: lpips
  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr 
      crop_border: 4
      test_y_channel: true
    ssim:
      type: ssim 
      crop_border: 4
      test_y_channel: true
    lpips:
      type: lpips 
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e9
  save_latest_freq: !!float 3e3
  show_tf_imgs_freq: !!float 1e3
  use_tb_logger: true

# wandb:
    # project: ESRGAN
    # resume_id: ~

# dist training settings
# dist_params:
  # backend: nccl
  # port: 16500 #29500
